using Jamiras.Commands;
using Jamiras.Components;
using Jamiras.DataModels;
using Jamiras.ViewModels;
using Jamiras.ViewModels.Fields;
using RATools.Data;
using RATools.Services;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Windows.Media;

namespace RATools.ViewModels
{
    [DebuggerDisplay("{Title} ({AssetType,nq})")]
    public abstract class AssetViewModelBase : GeneratedItemViewModelBase
    {
        public AssetViewModelBase(GameViewModel owner, AssetBase generatedAsset)
            : base(owner)
        {
            Generated = new AssetSourceViewModel(this, "Generated");
            if (generatedAsset != null)
                Generated.Asset = generatedAsset;

            Local = new AssetSourceViewModel(this, "Local");
            Published = new AssetSourceViewModel(this, "Published");

            if (owner == null || String.IsNullOrEmpty(owner.RACacheDirectory))
            {
                UpdateLocalCommand = DisabledCommand.Instance;
                DeleteLocalCommand = DisabledCommand.Instance;
            }
            else
            {
                UpdateLocalCommand = new DelegateCommand(UpdateLocal);
                DeleteLocalCommand = new DelegateCommand(DeleteLocal);
            }
        }

        protected abstract string AssetType { get; }

        public string AssetImage
        {
            get { return String.Format("/RATools;component/Resources/{0}.png", AssetType.ToLower()); }
        }

        /// <summary>
        /// The asset generated by the script.
        /// </summary>
        public AssetSourceViewModel Generated { get; private set; }
        /// <summary>
        /// The asset as saved on disk.
        /// </summary>
        public AssetSourceViewModel Local { get; private set; }
        /// <summary>
        /// The asset as saved on the server.
        /// </summary>
        public AssetSourceViewModel Published { get; private set; }

        /// <summary>
        /// The asset to compare with the generated asset.
        /// </summary>
        /// <remarks>
        /// References <see cref="Local"/>, <see cref="Published"/>, or null.
        /// </remarks>
        public AssetSourceViewModel Other { get; private set; }

        public CommandBase DeleteLocalCommand { get; protected set; }

        public virtual bool IsGenerated
        {
            get { return Generated.Asset != null; }
        }

        internal bool AllocateLocalId(int value)
        {
            // don't attempt to assign a temporary ID to a published asset
            if (Published != null && Published.Asset != null)
                return false;

            // if it's in the local file, generate a temporary ID if one was not previously generated
            if (Local != null && Local.Id == 0)
            {
                var localAsset = Local.Asset;
                if (localAsset != null)
                {
                    localAsset.Id = value;
                    Local.Asset = localAsset; // refresh the viewmodel's ID property
                    Id = Local.Id;
                    return true;
                }
            }

            // if it's not in the local file, generate a temporary ID if one was not provided by the code
            if (Generated != null && Generated.Id == 0)
            {
                var generatedAsset = Generated.Asset;
                if (generatedAsset != null)
                {
                    generatedAsset.Id = value;
                    Generated.Asset = generatedAsset; // refresh the viewmodel's ID property
                    Id = Generated.Id;
                    return true;
                }
            }

            return true;
        }

        public static readonly ModelProperty IdProperty = ModelProperty.Register(typeof(AssetViewModelBase), "Id", typeof(int), 0);
        public int Id
        {
            get { return (int)GetValue(IdProperty); }
            protected set { SetValue(IdProperty, value); }
        }

        public static readonly ModelProperty PointsProperty = ModelProperty.Register(typeof(AssetViewModelBase), "Points", typeof(int), 0);
        public int Points
        {
            get { return (int)GetValue(PointsProperty); }
            protected set { SetValue(PointsProperty, value); }
        }


        public static readonly ModelProperty IsPointsModifiedProperty = ModelProperty.Register(typeof(AssetViewModelBase), "IsPointsModified", typeof(bool), false);
        public bool IsPointsModified
        {
            get { return (bool)GetValue(IsPointsModifiedProperty); }
            protected set { SetValue(IsPointsModifiedProperty, value); }
        }

        protected void UpdateModified()
        {
            var coreAsset = Published.Asset;

            if (!IsGenerated)
            {
                ModificationMessage = null;
                CanUpdate = false;

                Other = null;
                IsTitleModified = false;
                IsDescriptionModified = false;
                IsPointsModified = false;
                CompareState = GeneratedCompareState.None;

                if (coreAsset != null)
                {
                    Triggers = Published.TriggerList;
                    if (coreAsset.IsUnofficial)
                        TriggerSource = "Unofficial (Not Generated)";
                    else
                        TriggerSource = "Core (Not Generated)";
                }
            }
            else if (IsModified(Local))
            {
                if (coreAsset != null && !IsModified(Published))
                {
                    if (coreAsset.IsUnofficial)
                        TriggerSource = "Generated (Same as Unofficial)";
                    else
                        TriggerSource = "Generated (Same as Core)";
                }
                else
                {
                    TriggerSource = "Generated";
                }

                Other = Local;
                ModificationMessage = "Local differs from generated";
                CompareState = GeneratedCompareState.LocalDiffers;
                CanUpdate = true;
            }
            else if (coreAsset != null && IsModified(Published))
            {
                if (Local.Asset != null)
                    TriggerSource = "Generated (Same as Local)";
                else
                    TriggerSource = "Generated (Not in Local)";

                Other = Published;
                if (coreAsset.IsUnofficial)
                    ModificationMessage = "Unofficial differs from generated";
                else
                    ModificationMessage = "Core differs from generated";

                CompareState = GeneratedCompareState.PublishedDiffers;
                CanUpdate = true;
            }
            else
            {
                if (Local.Asset == null && IsGenerated)
                {
                    if (coreAsset == null)
                        TriggerSource = "Generated (Not in Local)";
                    else if (coreAsset.IsUnofficial)
                        TriggerSource = "Generated (Same as Unofficial, not in Local)";
                    else
                        TriggerSource = "Generated (Same as Core, not in Local)";

                    ModificationMessage = "Local " + AssetType + " does not exist";
                    CompareState = GeneratedCompareState.PublishedMatchesNotGenerated;
                    CanUpdate = true;
                    Other = null;
                }
                else
                {
                    if (coreAsset == null)
                        TriggerSource = "Generated (Same as Local)";
                    else if (coreAsset.IsUnofficial)
                        TriggerSource = "Generated (Same as Unofficial and Local)";
                    else
                        TriggerSource = "Generated (Same as Core and Local)";

                    ModificationMessage = null;
                    CompareState = GeneratedCompareState.Same;
                    CanUpdate = false;
                    Other = null;
                }

                IsTitleModified = false;
                IsDescriptionModified = false;
                IsPointsModified = false;

                Triggers = Generated.TriggerList;
            }
        }

        protected bool IsModified(AssetSourceViewModel assetViewModel)
        {
            if (assetViewModel.Asset == null)
                return false;

            bool isModified = false;
            if (assetViewModel.Title.Text != Generated.Title.Text)
                IsTitleModified = isModified = true;
            if (assetViewModel.Description.Text != Generated.Description.Text)
                IsDescriptionModified = isModified = true;
            if (assetViewModel.Points.Value != Generated.Points.Value)
                IsPointsModified = isModified = true;

            var compareTriggers = new List<TriggerViewModel>(assetViewModel.TriggerList);
            var triggers = new List<TriggerViewModel>();
            var numberFormat = ServiceRepository.Instance.FindService<ISettings>().HexValues ? NumberFormat.Hexadecimal : NumberFormat.Decimal;
            var emptyTrigger = new TriggerViewModel("", (Achievement)null, numberFormat, null);

            foreach (var trigger in assetViewModel.TriggerList)
            {
                var compareTrigger = compareTriggers.FirstOrDefault(t => t.Label == trigger.Label);
                if (compareTrigger != null)
                    compareTriggers.Remove(compareTrigger);
                else
                    compareTrigger = emptyTrigger;

                triggers.Add(new TriggerComparisonViewModel(trigger, compareTrigger, numberFormat, _owner.Notes));
            }

            foreach (var compareTrigger in compareTriggers)
                triggers.Add(new TriggerComparisonViewModel(emptyTrigger, compareTrigger, numberFormat, _owner.Notes));

            Triggers = triggers;

            return isModified || 
                triggers.Any(t => t.Groups.Any(g => g.Requirements.OfType<RequirementComparisonViewModel>().Any(r => r.IsModified)));
        }

        public int SourceLine
        {
            get { return (Generated.Asset != null) ? Generated.Asset.SourceLine : 0; }
        }

        private void UpdateLocal()
        {
            StringBuilder warning = new StringBuilder();
            UpdateLocal(warning, false);

            if (warning.Length > 0)
                TaskDialogViewModel.ShowWarningMessage("Your " + AssetType + " may not function as expected.", warning.ToString());
        }

        internal void UpdateLocal(StringBuilder warning, bool validateAll)
        {
            var asset = Generated.Asset;
            if (asset.Id == 0)
                asset.Id = Id;

            if (String.IsNullOrEmpty(asset.BadgeName) || asset.BadgeName == "0")
                asset.BadgeName = BadgeName;

            UpdateLocal(asset, Local.Asset, warning, validateAll);

            Local = new AssetSourceViewModel(this, "Local");
            Local.Asset = Generated.Asset;

            OnPropertyChanged(() => Local);
            UpdateModified();
        }

        protected abstract void UpdateLocal(AssetBase asset, AssetBase localAsset, StringBuilder warning, bool validateAll);

        private void DeleteLocal()
        {
            UpdateLocal(null, Local.Asset, null, false);

            Local = new AssetSourceViewModel(this, "Local");
            OnPropertyChanged(() => Local);
            UpdateModified();
        }

        internal virtual void OnShowHexValuesChanged(ModelPropertyChangedEventArgs e)
        {
            foreach (var trigger in Triggers)
            {
                foreach (var group in trigger.Groups)
                    group.OnShowHexValuesChanged(e);
            }

            Generated.OnShowHexValuesChanged(e);
            Local.OnShowHexValuesChanged(e);
            Published.OnShowHexValuesChanged(e);
        }

        public static readonly ModelProperty BadgeProperty = ModelProperty.RegisterDependant(typeof(AssetViewModelBase), "Badge", typeof(ImageSource), new ModelProperty[0], GetBadge);
        public ImageSource Badge
        {
            get { return (ImageSource)GetValue(BadgeProperty); }
        }

        protected string BadgeName { get; set; }

        private static ImageSource GetBadge(ModelBase model)
        {
            var vm = (AssetViewModelBase)model;
            if (!String.IsNullOrEmpty(vm.Published.BadgeName))
                return vm.Published.Badge;
            if (!String.IsNullOrEmpty(vm.Local.BadgeName))
                return vm.Local.Badge;

            if (!String.IsNullOrEmpty(vm.BadgeName))
            {
                vm.Local.BadgeName = vm.BadgeName;
                return vm.Local.Badge;
            }

            return null;
        }

        public override void Refresh()
        {
            var generatedAsset = Generated.Asset;
            var localAsset = Local.Asset;
            var coreAsset = Published.Asset;

            Published.Source = (coreAsset == null) ? "Published" :
                coreAsset.IsUnofficial ? "Published (Unofficial)" : "Published (Core)";

            if (generatedAsset != null)
                BindViewModel(Generated);
            else if (coreAsset != null)
                LoadViewModel(Published);
            else if (localAsset != null)
                LoadViewModel(Local);

            if (Generated.Id != 0)
                Id = Generated.Id;
            else if (Local.Id != 0)
                Id = Local.Id;
            else
                Id = Published.Id;

            if (!String.IsNullOrEmpty(Generated.BadgeName) && Generated.BadgeName != "0")
                BadgeName = Generated.BadgeName;
            else if (!String.IsNullOrEmpty(Local.BadgeName) && Local.BadgeName != "0")
                BadgeName = Local.BadgeName;
            else if (!String.IsNullOrEmpty(Published.BadgeName) && Published.BadgeName != "0")
                BadgeName = Published.BadgeName;
            else
                BadgeName = null;

            UpdateModified();

            base.Refresh();
        }

        private void BindViewModel(AssetSourceViewModel viewModel)
        {
            SetBinding(TitleProperty, new ModelBinding(viewModel.Title, TextFieldViewModel.TextProperty, ModelBindingMode.OneWay));
            SetBinding(DescriptionProperty, new ModelBinding(viewModel.Description, TextFieldViewModel.TextProperty, ModelBindingMode.OneWay));
            SetBinding(PointsProperty, new ModelBinding(viewModel.Points, IntegerFieldViewModel.ValueProperty, ModelBindingMode.OneWay));
        }

        private void LoadViewModel(AssetSourceViewModel viewModel)
        {
            Title = viewModel.Title.Text;
            Description = viewModel.Description.Text;
            Points = viewModel.Points.Value.GetValueOrDefault();
        }

        public static readonly ModelProperty TriggerSourceProperty =
            ModelProperty.Register(typeof(AssetViewModelBase), "TriggerSource", typeof(string), "Generated");

        public string TriggerSource
        {
            get { return (string)GetValue(TriggerSourceProperty); }
            private set { SetValue(TriggerSourceProperty, value); }
        }

        public static readonly ModelProperty TriggersProperty = ModelProperty.Register(typeof(AssetViewModelBase),
            "Triggers", typeof(IEnumerable<TriggerViewModel>), new TriggerViewModel[0]);

        public IEnumerable<TriggerViewModel> Triggers
        {
            get { return (IEnumerable<TriggerViewModel>)GetValue(TriggersProperty); }
            private set { SetValue(TriggersProperty, value); }
        }

        internal abstract IEnumerable<TriggerViewModel> BuildTriggerList(AssetSourceViewModel assetViewModel);
    }
}
