using RATools.Data;
using RATools.Parser.Expressions;
using RATools.Parser.Internal;
using System.Diagnostics;
using System.Linq;

namespace RATools.Parser.Functions
{
    internal class AchievementFunction : FunctionDefinitionExpression
    {
        public AchievementFunction()
            : base("achievement")
        {
            // required parameters
            Parameters.Add(new VariableDefinitionExpression("title"));
            Parameters.Add(new VariableDefinitionExpression("description"));
            Parameters.Add(new VariableDefinitionExpression("points"));
            Parameters.Add(new VariableDefinitionExpression("trigger"));

            // additional parameters generated by dumper
            Parameters.Add(new VariableDefinitionExpression("id"));
            DefaultParameters["id"] = new IntegerConstantExpression(0);
            Parameters.Add(new VariableDefinitionExpression("published"));
            DefaultParameters["published"] = new StringConstantExpression("");
            Parameters.Add(new VariableDefinitionExpression("modified"));
            DefaultParameters["modified"] = new StringConstantExpression("");
            Parameters.Add(new VariableDefinitionExpression("badge"));
            DefaultParameters["badge"] = new StringConstantExpression("00000");

            Parameters.Add(new VariableDefinitionExpression("type"));
            DefaultParameters["type"] = new StringConstantExpression("");
            Parameters.Add(new VariableDefinitionExpression("set"));
            DefaultParameters["set"] = new IntegerConstantExpression(0);
        }

        public override bool DelayError(string parameterName)
        {
            return true;
        }

        public override bool Evaluate(InterpreterScope scope, out ExpressionBase result)
        {
            var achievement = new ScriptInterpreterAchievementBuilder();

            var stringExpression = GetStringParameter(scope, "title", out result);
            if (stringExpression != null)
                achievement.Title = stringExpression.Value;
            else
                scope.ReturnValue ??= result;

            stringExpression = GetStringParameter(scope, "description", out result);
            if (stringExpression != null)
                achievement.Description = stringExpression.Value;
            else
                scope.ReturnValue ??= result;

            stringExpression = GetStringParameter(scope, "badge", out result);
            if (stringExpression != null)
                achievement.BadgeName = stringExpression.Value;
            else
                scope.ReturnValue ??= result;

            var integerExpression = GetIntegerParameter(scope, "points", out result);
            if (integerExpression == null)
                scope.ReturnValue ??= result;
            else if (!Achievement.ValidPointValues.Contains(integerExpression.Value))
                scope.ReturnValue ??= new ErrorExpression(integerExpression.Value + " is not a supported value for points", integerExpression);
            else
                achievement.Points = integerExpression.Value;

            integerExpression = GetIntegerParameter(scope, "id", out result);
            if (integerExpression != null)
                achievement.Id = integerExpression.Value;
            else
                scope.ReturnValue ??= result;

            stringExpression = GetStringParameter(scope, "published", out result);
            if (stringExpression != null && !string.IsNullOrEmpty(stringExpression.Value))
                achievement.IsDumped = true;

            stringExpression = GetStringParameter(scope, "type", out result);
            if (stringExpression == null)
            {
                scope.ReturnValue ??= result;
            }
            else
            {
                achievement.Type = Achievement.ParseType(stringExpression.Value);
                if (achievement.Type == AchievementType.None)
                    scope.ReturnValue ??= new ErrorExpression(stringExpression.Value + " is not a supported achievement type", stringExpression);
            }

            var context = scope.GetContext<AchievementScriptContext>();
            Debug.Assert(context != null);
            AchievementSet set = null;

            integerExpression = GetIntegerParameter(scope, "set", out result);
            if (integerExpression == null)
            {
                scope.ReturnValue ??= result;
            }
            else if (integerExpression.Value != 0)
            {
                set = context.GetSet(integerExpression.Value);
                if (set == null)
                    scope.ReturnValue ??= new ErrorExpression("Unknown set id: " + integerExpression.Value, integerExpression);
            }

            var trigger = GetRequirementParameter(scope, "trigger", out result);
            if (trigger == null)
            {
                scope.ReturnValue ??= result;
            }
            else if (!TriggerBuilderContext.ProcessAchievementConditions(achievement, trigger, scope, out result))
            {
                if (result.Location.Start != trigger.Location.Start || result.Location.End != trigger.Location.End)
                {
                    var error = (ErrorExpression)result;
                    scope.ReturnValue ??= new ErrorExpression(error.Message, trigger) { InnerError = error };
                }
                else
                {
                    scope.ReturnValue ??= result;
                }
            }

            var newAchievement = achievement.ToAchievement();
            newAchievement.OwnerSetId = set?.OwnerSetId ?? 0;
            newAchievement.OwnerGameId = set?.OwnerGameId ?? context?.GameId ?? 0;

            var sourceLine = 0;
            var functionCall = scope.GetOutermostContext<FunctionCallExpression>();
            if (functionCall != null)
                sourceLine = functionCall.Location.Start.Line;

            context.Achievements[newAchievement] = sourceLine;

            result = scope.ReturnValue;
            if (result != null)
            {
                newAchievement.IsInvalid = true;
                return false;
            }

            return true;
        }
    }
}
