name: C# CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, github-actions ]

jobs:
  Build-and-Tests:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x

    - name: Install MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Install dependencies
      run: dotnet restore RATools.sln

    - name: Build
      run: msbuild.exe RATools.sln -p:Configuration=Release -p:Platform="Any CPU"

    - name: Run Data Tests
      run: dotnet test Tests\Data\bin\Release\net6.0-windows\RATools.Data.Tests.dll

    - name: Run Parser Tests
      run: dotnet test Tests\Parser\bin\Release\net6.0-windows\RATools.Parser.Tests.dll

    - name: Run RATools Tests
      run: dotnet test Tests\bin\Release\net6.0-windows\RATools.Tests.dll
